run:
  timeout: 3m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - ineffassign
    - errcheck
    - gosimple

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
  gofmt:
    simplify: true
  goimports:
    local-prefixes: say11

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
